# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: ubuntu:bionic
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/dyindude.discord
    environment:
      ANSIBLE_VERSION: "2.1.1.0"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dep-{{ .Environment.ANSIBLE_VERSION }}
          # fallback to using the latest cache if no exact match is found
          - v1-dep-

      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get -y install python python-dev python-virtualenv
            python -m virtualenv ~/venv
            . ~/venv/bin/activate
            pip install --upgrade pip "ansible==$ANSIBLE_VERSION"
            echo '[defaults]' >> ansible.cfg
            echo 'roles_path = ../' >> ansible.cfg
            echo 'host_key_checking = False' >> ansible.cfg

      - save_cache:
          paths:
            - ./~venv
            - ./ansible.cfg
          key: v1-dep-{{ .Environment.ANSIBLE_VERSION }}
        
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            ansible-playbook -i tests/inventory tests/test.yml
            ansible-playbook -i tests/inventory tests/test.yml
